---
- name: Adding GPG key for K8S packges
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
- name: Installing Curl if not installed before
  apt: name=curl state=present
- name: Adding K8S repo to sources
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'
- name: Finally Installing Kube packges
  apt: 
    name: "{{ kube_packages }}"
    state: present
    

