---
- name: Kubernetes Intilaization
  shell : kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
  args:
    chdir: /home/{{ ansible_user }}
    creates: cluster_initalization_info.txt
- name: creating directory to hold cluster congiguation
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    mode: 0755
    owner: raghu
    group: raghu
- name: copying the config files
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
- name: Setting up pod network to establish communication between nodes
  become_user: "{{ ansible_user }}"
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_info.txt
  args:
    chdir: /home/{{ ansible_user }}
    creates: pod_network_info.txt
- name: running join command 
  shell: "kubeadm token create --print-join-command"
  register: join_cmd
- name: copying the content of join command to local
  local_action: copy content={{ join_cmd.stdout }} dest={{ token_file }}
  

